apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "arkime.fullname" . }}-central-viewer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "arkime.labels" . | nindent 4 }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.centralViewer.replicas }}
  revisionHistoryLimit: {{ .Values.centralViewer.revisionHistoryLimit }}
  {{- with .Values.centralViewer.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "arkime.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "arkime.selectorLabels" . | nindent 8 }}
      {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      annotations:
        {{- with .Values.centralViewer.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.centralViewer.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "arkime.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.centralViewer.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      {{- with .Values.centralViewer.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      {{- with .Values.centralViewer.dnsPolicy }}
      dnsPolicy: {{ . }}
      {{- end }}
      {{- with .Values.centralViewer.dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8}}
      {{- end }}
      {{- if .Values.centralViewer.hostNetwork }}
      hostNetwork: true
      {{- end }}
      {{- with .Values.centralViewer.schedulerName }}
      schedulerName: {{ . | quote }}
      {{- end }}
      {{- with .Values.centralViewer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
      - name: arkime-db-init
        image: "{{ .Values.centralViewer.image.repository }}:{{ .Values.centralViewer.image.tag }}"
        imagePullPolicy: {{ .Values.centralViewer.imagePullPolicy }}
        command: ["/opt/arkime/db/db.pl", "--insecure", "--esuser", "admin:admin", {{ .Values.settings.elasticsearch }}, "init", "--ifneeded" ]
      containers:
        - name: arkime-central-viewer
          image: "{{ .Values.centralViewer.image.repository }}:{{ .Values.centralViewer.image.tag }}"
          imagePullPolicy: {{ .Values.centralViewer.imagePullPolicy }}
          command:
            {{- toYaml .Values.centralViewer.command | nindent 12 }}
          env:
            - name: ARKIME__elasticsearch
              value: "{{ .Values.settings.elasticsearch }}"
          {{- with .Values.centralViewer.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- toYaml .Values.centralViewer.env | nindent 12 }}
          {{- with .Values.centralViewer.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
          - name: arkime-config
            mountPath: /opt/arkime/etc/
      volumes:
      - name: arkime-config
        configMap:
          name: {{ include "arkime.fullname" . }}-config-map