apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "arkime.fullname" . }}-opensearch
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "arkime.labels" . | nindent 4 }}
  {{- with .Values.opensearch.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.opensearch.replicas }}
  revisionHistoryLimit: {{ .Values.opensearch.revisionHistoryLimit }}
  {{- with .Values.opensearch.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "arkime.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "arkime.selectorLabels" . | nindent 8 }}
      {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      annotations:
        {{- with .Values.opensearch.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.opensearch.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "arkime.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.opensearch.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      {{- with .Values.opensearch.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      {{- with .Values.opensearch.dnsPolicy }}
      dnsPolicy: {{ . }}
      {{- end }}
      {{- with .Values.opensearch.dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8}}
      {{- end }}
      {{- if .Values.opensearch.hostNetwork }}
      hostNetwork: true
      {{- end }}
      {{- with .Values.opensearch.schedulerName }}
      schedulerName: {{ . | quote }}
      {{- end }}
      {{- with .Values.opensearch.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: arkime-viewer
          image: "{{ .Values.opensearch.image.repository }}:{{ .Values.opensearch.image.tag }}"
          imagePullPolicy: {{ .Values.opensearch.imagePullPolicy }}
          ports:
            - containerPort: 9200
              name: opensearch-http
          livenessProbe:
          {{- with .Values.opensearch.livenessProbe }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
          {{- with .Values.opensearch.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.opensearch.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
          - name: arkime-config
            mountPath: /opt/arkime/etc/
      volumes:
      - name: arkime-config
        configMap:
          name: {{ include "arkime.fullname" . }}-config-map
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "arkime.labels" . | nindent 4 }}
  {{- with .Values.opensearch.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- include "arkime.selectorLabels" . | nindent 4 }}
  ports:
  - name: opensearch
    protocol: TCP
    port: 9200
    targetPort: opensearch-http